/*
 * Automatically generated by "tools/bmp_logo"
 *
 * DO NOT EDIT
 *
 */


#ifndef __BMP_LOGO_LU300_H__
#define __BMP_LOGO_LU300_H__

#define BMP_LOGO_WIDTH_LU300		240
#define BMP_LOGO_HEIGHT_LU300		320
#define BMP_LOGO_COLORS_LU300		240
#define BMP_LOGO_OFFSET_LU300		16

extern unsigned short bmp_logo_palette_lu300[];
extern unsigned char bmp_logo_bitmap_lu300[];

#endif /* __BMP_LOGO_LU300_H__ */
